version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"  # Map to 8080 on host to avoid conflict with backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

  backend:
    build: ./backend
    ports:
      - "3000:3000"  # Your backend runs on port 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://22ce086:Dishang%231135@cluster0.dtr8dni.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key-change-in-production
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:8080  # Frontend will be on 8080

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: